# Generated by Django 3.2.6 on 2021-09-06 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url_tocken',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='linkuse',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jumps', to='api.link'),
        ),
    ]
