# Generated by Django 3.2.6 on 2021-09-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210906_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkuse',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
